import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import AppLayout from '@/layouts/app-layout';
import { WizardAnalysisListItem } from '@/types/wizard';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { ExternalLink, FileDown, Sparkles, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

// Route will be auto-generated by wayfinder

interface PageProps extends Record<string, unknown> {
    analyses: WizardAnalysisListItem[];
}

function ConfidenceBadge({
    confidence,
}: {
    confidence: 'high' | 'medium' | 'low';
}) {
    const config = {
        high: { label: 'Yüksek', className: 'bg-green-500 text-white' },
        medium: { label: 'Orta', className: 'bg-yellow-500 text-white' },
        low: { label: 'Düşük', className: 'bg-orange-500 text-white' },
    };

    const { label, className } = config[confidence];

    return <Badge className={className}>{label} Güven</Badge>;
}

export default function WizardAnalysesIndex() {
    const { analyses } = usePage<PageProps>().props;

    const handleDelete = (id: number) => {
        if (!confirm('Bu analizi silmek istediğinize emin misiniz?')) {
            return;
        }

        router.delete(`/wizard/analyses/${id}`, {
            preserveScroll: true,
            onSuccess: () => {
                toast.success('Analiz başarıyla silindi');
            },
            onError: () => {
                toast.error('Bir hata oluştu');
            },
        });
    };

    const formatDate = (dateString: string) => {
        const date = new Date(dateString);
        return new Intl.DateTimeFormat('tr-TR', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        }).format(date);
    };

    return (
        <AppLayout>
            <Head title="Analizlerim" />
            <div className="container mx-auto px-4 py-8">
                <div className="mb-8">
                    <h1 className="mb-2 text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                        Analizlerim
                    </h1>
                    <p className="text-zinc-500 dark:text-zinc-400">
                        Geçmiş platform öneri analizleriniz
                    </p>
                </div>

                {analyses.length === 0 ? (
                    <div className="py-20 text-center">
                        <Sparkles className="mx-auto mb-4 h-16 w-16 text-zinc-300 dark:text-zinc-700" />
                        <h3 className="mb-2 text-xl font-semibold text-zinc-900 dark:text-zinc-50">
                            Henüz analiz yok
                        </h3>
                        <p className="mb-6 text-zinc-500 dark:text-zinc-400">
                            Platform önerisi almak için wizard'ı başlatın
                        </p>
                        <Button asChild>
                            <Link href="/wizard">Wizard Başlat</Link>
                        </Button>
                    </div>
                ) : (
                    <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                        {analyses.map((analysis) => (
                            <Card
                                key={analysis.id}
                                className="overflow-hidden transition-shadow hover:shadow-lg"
                            >
                                <CardHeader>
                                    <div className="mb-2 flex items-start justify-between">
                                        <div className="flex-1">
                                            {analysis.platform ? (
                                                <div className="mb-2 flex items-center gap-3">
                                                    {analysis.platform.logo && (
                                                        <img
                                                            src={
                                                                analysis
                                                                    .platform
                                                                    .logo
                                                            }
                                                            alt={
                                                                analysis
                                                                    .platform
                                                                    .name
                                                            }
                                                            className="h-10 w-auto dark:hidden"
                                                        />
                                                    )}
                                                    {analysis.platform
                                                        .dark_logo && (
                                                        <img
                                                            src={
                                                                analysis
                                                                    .platform
                                                                    .dark_logo
                                                            }
                                                            alt={
                                                                analysis
                                                                    .platform
                                                                    .name
                                                            }
                                                            className="hidden h-10 w-auto dark:block"
                                                        />
                                                    )}
                                                    <CardTitle className="text-lg">
                                                        {analysis.platform.name}
                                                    </CardTitle>
                                                </div>
                                            ) : (
                                                <CardTitle className="text-lg">
                                                    Platform Önerisi
                                                </CardTitle>
                                            )}
                                            {analysis.plan && (
                                                <p className="text-sm text-muted-foreground">
                                                    {analysis.plan.name} - $
                                                    {analysis.plan.monthlyPrice}
                                                    /
                                                    {analysis.plan.currency ===
                                                    'USD'
                                                        ? 'ay'
                                                        : analysis.plan
                                                              .currency}
                                                </p>
                                            )}
                                        </div>
                                        <ConfidenceBadge
                                            confidence={analysis.confidence}
                                        />
                                    </div>
                                    <div className="mt-2 flex items-center gap-4">
                                        <div className="text-center">
                                            <div className="text-2xl font-bold text-primary">
                                                {analysis.score}
                                            </div>
                                            <div className="text-xs text-muted-foreground">
                                                Puan
                                            </div>
                                        </div>
                                        <div className="flex-1 text-xs text-muted-foreground">
                                            {formatDate(analysis.created_at)}
                                        </div>
                                    </div>
                                </CardHeader>
                                <CardContent className="space-y-2">
                                    <div className="flex gap-2">
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="flex-1"
                                            asChild
                                        >
                                            <Link
                                                href={`/wizard/analyses/${analysis.id}`}
                                            >
                                                <ExternalLink className="mr-2 h-4 w-4" />
                                                Detayları Gör
                                            </Link>
                                        </Button>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="flex-1"
                                            asChild
                                        >
                                            <Link
                                                href={`/wizard/analyses/${analysis.id}/pdf`}
                                            >
                                                <FileDown className="mr-2 h-4 w-4" />
                                                PDF İndir
                                            </Link>
                                        </Button>
                                    </div>
                                    <Button
                                        variant="ghost"
                                        size="sm"
                                        className="w-full text-red-600 hover:bg-red-50 hover:text-red-700 dark:hover:bg-red-950/20"
                                        onClick={() =>
                                            handleDelete(analysis.id)
                                        }
                                    >
                                        <Trash2 className="mr-2 h-4 w-4" />
                                        Sil
                                    </Button>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )}
            </div>
        </AppLayout>
    );
}
