import AppLayout from '@/layouts/app-layout';
import { Head, usePage, Link, router } from '@inertiajs/react';
import { WizardAnalysisListItem } from '@/types/wizard';
import { FileDown, Trash2, ExternalLink, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
// Route will be auto-generated by wayfinder

interface PageProps extends Record<string, unknown> {
    analyses: WizardAnalysisListItem[];
}

function ConfidenceBadge({ confidence }: { confidence: 'high' | 'medium' | 'low' }) {
    const config = {
        high: { label: 'Yüksek', className: 'bg-green-500 text-white' },
        medium: { label: 'Orta', className: 'bg-yellow-500 text-white' },
        low: { label: 'Düşük', className: 'bg-orange-500 text-white' },
    };

    const { label, className } = config[confidence];

    return (
        <Badge className={className}>
            {label} Güven
        </Badge>
    );
}

export default function WizardAnalysesIndex() {
    const { analyses } = usePage<PageProps>().props;

    const handleDelete = (id: number) => {
        if (!confirm('Bu analizi silmek istediğinize emin misiniz?')) {
            return;
        }

        router.delete(`/wizard/analyses/${id}`, {
            preserveScroll: true,
            onSuccess: () => {
                toast.success('Analiz başarıyla silindi');
            },
            onError: () => {
                toast.error('Bir hata oluştu');
            },
        });
    };

    const formatDate = (dateString: string) => {
        const date = new Date(dateString);
        return new Intl.DateTimeFormat('tr-TR', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        }).format(date);
    };

    return (
        <AppLayout>
            <Head title="Analizlerim" />
            <div className="container mx-auto px-4 py-8">
                <div className="mb-8">
                    <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50 mb-2">
                        Analizlerim
                    </h1>
                    <p className="text-zinc-500 dark:text-zinc-400">
                        Geçmiş platform öneri analizleriniz
                    </p>
                </div>

                {analyses.length === 0 ? (
                    <div className="text-center py-20">
                        <Sparkles className="h-16 w-16 text-zinc-300 dark:text-zinc-700 mx-auto mb-4" />
                        <h3 className="text-xl font-semibold text-zinc-900 dark:text-zinc-50 mb-2">
                            Henüz analiz yok
                        </h3>
                        <p className="text-zinc-500 dark:text-zinc-400 mb-6">
                            Platform önerisi almak için wizard'ı başlatın
                        </p>
                        <Button asChild>
                            <Link href="/wizard">Wizard Başlat</Link>
                        </Button>
                    </div>
                ) : (
                    <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
                        {analyses.map((analysis) => (
                            <Card key={analysis.id} className="overflow-hidden hover:shadow-lg transition-shadow">
                                <CardHeader>
                                    <div className="flex items-start justify-between mb-2">
                                        <div className="flex-1">
                                            {analysis.platform ? (
                                                <div className="flex items-center gap-3 mb-2">
                                                    {analysis.platform.logo && (
                                                        <img
                                                            src={analysis.platform.logo}
                                                            alt={analysis.platform.name}
                                                            className="h-10 w-auto dark:hidden"
                                                        />
                                                    )}
                                                    {analysis.platform.dark_logo && (
                                                        <img
                                                            src={analysis.platform.dark_logo}
                                                            alt={analysis.platform.name}
                                                            className="h-10 w-auto hidden dark:block"
                                                        />
                                                    )}
                                                    <CardTitle className="text-lg">
                                                        {analysis.platform.name}
                                                    </CardTitle>
                                                </div>
                                            ) : (
                                                <CardTitle className="text-lg">Platform Önerisi</CardTitle>
                                            )}
                                            {analysis.plan && (
                                                <p className="text-sm text-muted-foreground">
                                                    {analysis.plan.name} - ${analysis.plan.monthlyPrice}/{analysis.plan.currency === 'USD' ? 'ay' : analysis.plan.currency}
                                                </p>
                                            )}
                                        </div>
                                        <ConfidenceBadge confidence={analysis.confidence} />
                                    </div>
                                    <div className="flex items-center gap-4 mt-2">
                                        <div className="text-center">
                                            <div className="text-2xl font-bold text-primary">
                                                {analysis.score}
                                            </div>
                                            <div className="text-xs text-muted-foreground">Puan</div>
                                        </div>
                                        <div className="flex-1 text-xs text-muted-foreground">
                                            {formatDate(analysis.created_at)}
                                        </div>
                                    </div>
                                </CardHeader>
                                <CardContent className="space-y-2">
                                    <div className="flex gap-2">
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="flex-1"
                                            asChild
                                        >
                                            <Link href={`/wizard/analyses/${analysis.id}`}>
                                                <ExternalLink className="h-4 w-4 mr-2" />
                                                Detayları Gör
                                            </Link>
                                        </Button>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            className="flex-1"
                                            asChild
                                        >
                                            <Link href={`/wizard/analyses/${analysis.id}/pdf`}>
                                                <FileDown className="h-4 w-4 mr-2" />
                                                PDF İndir
                                            </Link>
                                        </Button>
                                    </div>
                                    <Button
                                        variant="ghost"
                                        size="sm"
                                        className="w-full text-red-600 hover:text-red-700 hover:bg-red-50 dark:hover:bg-red-950/20"
                                        onClick={() => handleDelete(analysis.id)}
                                    >
                                        <Trash2 className="h-4 w-4 mr-2" />
                                        Sil
                                    </Button>
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )}
            </div>
        </AppLayout>
    );
}

